FROM python:3.12-slim

RUN pip install --upgrade pip

RUN pip install streamlit==1.44.1 httpx==0.28.1 pydantic_settings==2.8.1

WORKDIR /app

ENV PYTHONPATH=/app/src

CMD ["streamlit", "run", "src/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

