services:
  api:
    image: mydrift-api
    container_name: mydrift-api
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true

  dev:
    image: mydrift-dev
    container_name: mydrift-dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true
