services:
  api:
    image: api
    container_name: api
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: python3 src/run_api.py

  dev:
    image: dev
    container_name: dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true

  qdrant:
    image: qdrant/qdrant:v1.13.5
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ../data/qdrant:/qdrant/storage
    restart: unless-stopped

  streamlit_ui:
    build:
      context: ../ui
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    volumes:
      - ../ui:/app
      - ../data/message:/app/message
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
  