services:
  api:
    image: mydrift-api
    container_name: mydrift-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true
