services:
  api:
    image: api
    container_name: api
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true

  dev:
    image: dev
    container_name: dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ../data/mongodb:/data/db

  mongo-express:
    image: mongo-express:1-18
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  qdrant:
    image: qdrant/qdrant:v1.13.5
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ../data/qdrant_data:/qdrant/storage
    restart: unless-stopped

  streamlit_ui:
    build:
      context: ../ui
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    volumes:
      - ../data/streamlit:/app/data  # 如果你有共享資料夾（例如 messages.json 放這）
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
