name: Run PR Agent Review (on label)

on:
  pull_request:
    types: [labeled]

jobs:
  pr-review:
    if: contains(github.event.pull_request.labels.*.name, 'run-review')
    runs-on: ubuntu-latest

    env:
      OPENAI.KEY: ${{ secrets.OPENAI_KEY }}
      GITHUB.USER_TOKEN: ${{ secrets.GH_USER_TOKEN }}

    steps:
      - name: Run CodiumAI PR Agent
        run: |
          docker run --rm -i \
            -e OPENAI.KEY="$OPENAI.KEY" \
            -e GITHUB.USER_TOKEN="$GITHUB.USER_TOKEN" \
            codiumai/pr-agent:latest \
            --pr_url "${{ github.event.pull_request.html_url }}" review
      - name: Remove `run-review` label after run
        run: |
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GH_USER_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/run-review
